junction/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('zalando.urls')),
]

zalando/urls.py
from django.conf.urls import url
from . import views

app_name = 'zalando'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.ArticleDetailView.as_view(), name='detail'),
]

zalando/models.py
from django.db import models


# Create your models here.
class Article(models.Model):
    name = models.CharField(max_length=100)
    shop_id = models.CharField(max_length=100)
    shop_url = models.URLField()


class ArticleImage(models.Model):
    article = models.ForeignKey(Article, related_name='images')
    url = models.URLField()


class Track(models.Model):
    article = models.ForeignKey(Article, related_name='tracks')
    track_id = models.CharField(max_length=100)

zalando/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from .models import Article


# Create your views here.
class IndexView(ListView):
    model = Article
    template_name = 'zalando/index.html'
    paginate_by = 12

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        return context


class ArticleDetailView(DetailView):
    model = Article
    template_name = 'zalando/detail.html'

    def get_context_data(self, **kwargs):
        context = super(ArticleDetailView, self).get_context_data(**kwargs)
        return context

zalando/templates/zalando/base.html
<!DOCTYPE html>
<html>
<head>
    <title>Zalandeezer</title>

    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

    <link rel="stylesheet" href="//cdn.jsdelivr.net/foundation/6.2.4/foundation.min.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/motion-ui/1.1.1/motion-ui.min.css"/>

    <style>
        body {
            background: #f36120;
        }
    </style>
</head>
<body>

<div class="top-bar">
    <div class="top-bar-title">
        <a href="{% url 'zalando:index' %}"><h4>ZalanDeezer</h4></a>
    </div>
    <div class="top-bar-right">
        <ul class="menu">
            <li><img
                    height=40
                    width=40
                    src="//lh6.googleusercontent.com/-3ifk7zbKpd8/AAAAAAAAAAI/AAAAAAAAPeA/5TVE5tmewJ4/s0-c-k-no-ns/photo.png"
                    alt="Zalando"></li>
            <li><img
                    height=40
                    width=40
                    src="//www.telenor.me/media/Usluge/All/deezer_ico.png"
                    alt="Deezer"></li>
        </ul>
    </div>
</div>

{#<div class="top-bar">#}
{#    <div class="top-bar-title">#}
{#    <span data-responsive-toggle="responsive-menu" data-hide-for="medium">#}
{#      <button class="menu-icon dark" type="button" data-toggle></button>#}
{#    </span>#}
{#        <strong>ZalanDeezer</strong>#}
{#    </div>#}
{#    <div id="responsive-menu">#}
{#        <div class="top-bar-left">#}
{#            <ul class="dropdown menu" data-dropdown-menu>#}
{#                <li>#}
{#                    <a href="#">One</a>#}
{#                    <ul class="menu vertical">#}
{#                        <li><a href="#">One</a></li>#}
{#                        <li><a href="#">Two</a></li>#}
{#                        <li><a href="#">Three</a></li>#}
{#                    </ul>#}
{#                </li>#}
{#                <li><a href="#">Two</a></li>#}
{#                <li><a href="#">Three</a></li>#}
{#            </ul>#}
{#        </div>#}
{#        <div class="top-bar-right">#}
{#            <ul class="menu">#}
{#                <li><input type="search" placeholder="Search"></li>#}
{#                <li>#}
{#                    <button type="button" class="button">Search</button>#}
{#                </li>#}
{#            </ul>#}
{#        </div>#}
{#    </div>#}
{#</div>#}

<script src="//cdn.jsdelivr.net/jquery/3.1.1/jquery.min.js"></script>
<script src="//cdn.jsdelivr.net/foundation/6.2.4/foundation.min.js"></script>

{% block body %}
{% endblock body %}
</body>
</html>

zalando/templates/zalando/detail.html
{% extends './base.html' %}

{% block body %}

    <div class="large-4 large-offset-4 medium-6 medium-offset-3 small-10 small-offset-1 columns">
        <div class="orbit" role="region" aria-label="Favorite Space Pictures" data-orbit>
            <ul class="orbit-container">
                <button class="orbit-previous"><span class="show-for-sr">Previous Slide</span>&#9664;&#xFE0E;</button>
                <button class="orbit-next"><span class="show-for-sr">Next Slide</span>&#9654;&#xFE0E;</button>
                {% for image in object.images.all %}
                    {% if forloop.counter == 1 %}
                        <li class="is-active orbit-slide">
                            <img class="orbit-image" src="{{ image.url }}" alt="{{ object.name }}">
                            <figcaption class="orbit-caption">{{ object.name }}</figcaption>
                        </li>
                    {% else %}
                        <li class="orbit-slide">
                            <img class="orbit-image" src="{{ image.url }}" alt="{{ object.name }}">
                            <figcaption class="orbit-caption">{{ object.name }}</figcaption>
                        </li>
                    {% endif %}
                {% endfor %}
            </ul>
            <nav class="orbit-bullets">
                {% for image in object.images.all %}
                    {% if forloop.counter == 1 %}
                        <button class="is-active" data-slide="{{ forloop.counter0 }}">
                            <span class="show-for-sr">{{ object.name }}</span>
                        </button>
                    {% else %}
                        <button data-slide="{{ forloop.counter0 }}">
                            <span class="show-for-sr">{{ object.name }}</span>
                        </button>
                    {% endif %}
                {% endfor %}
            </nav>
        </div>

        <div>
            <a class="button" target="_blank" href="{{ object.shop_url }}">Go To Shop</a>
        </div>

        {% if object.tracks.first %}
            <iframe scrolling="no" frameborder="0" allowTransparency="true"
                    src="//www.deezer.com/plugins/player?format=classic&autoplay=true&playlist=false&width=700&height=350&color=007FEB&layout=&size=medium&type=tracks&id={{ object.tracks.first.track_id }}&app_id=1"
                    width="500" height="100"></iframe>

        {% else %}
            <p>No music</p>
        {% endif %}

    </div>

    <script type="text/javascript">
        const e = $('.orbit')
        new Foundation.Orbit(e, {
            timerDelay: 2500
        })
    </script>

{% endblock body %}

zalando/templates/zalando/index.html
{% extends './base.html' %}

{% block body %}
<div>
    {% if is_paginated %}
    <ul class="pagination text-center" role="navigation" aria-label="Pagination">
        {% if page_obj.has_previous %}
        <li class="pagination-previous"><a href="{% url 'zalando:index' %}?page={{ page_obj.previous_page_number }}">Previous</a>
        </li>
        {% else %}
        <li class="pagination-previous disabled">Previous</li>
        {% endif %}
        <li class="current"><span class="show-for-sr">
            You're on page</span> {{ page_obj.number }} / {{ page_obj.paginator.num_pages }}
        </li>
        {% if page_obj.has_next %}
        <li class="pagination-next"><a href="{% url 'zalando:index' %}?page={{ page_obj.next_page_number }}">Next</a>
        </li>
        {% else %}
        <li class="pagination-next disabled">Next</li>
        {% endif %}
    </ul>
    {% endif %}

    <div class="row">
        {% for article in object_list %}
        <div class="small-6 medium-4 large-3 columns">
            <a href="{% url 'zalando:detail' article.id %}">
                <figure>
                    <img src="{{ article.images.first.url }}">
                </figure>
            </a>
        </div>
        {% empty %}
        <div class="small-6 large-4 columns">No articles yet.</div>
        {% endfor %}
    </div>

    {% if is_paginated %}
    <ul class="pagination text-center" role="navigation" aria-label="Pagination">
        {% if page_obj.has_previous %}
        <li class="pagination-previous"><a href="{% url 'zalando:index' %}?page={{ page_obj.previous_page_number }}">Previous</a>
        </li>
        {% else %}
        <li class="pagination-previous disabled">Previous</li>
        {% endif %}
        <li class="current"><span class="show-for-sr">
            You're on page</span> {{ page_obj.number }} / {{ page_obj.paginator.num_pages }}
        </li>
        {% if page_obj.has_next %}
        <li class="pagination-next"><a href="{% url 'zalando:index' %}?page={{ page_obj.next_page_number }}">Next</a>
        </li>
        {% else %}
        <li class="pagination-next disabled">Next</li>
        {% endif %}
    </ul>
    {% endif %}
</div>
{% endblock body %}